project:
  type: book

book:
  title: "SGV 101"
  author: "Dimitri Masson"
  date: "14/11/2024"
  chapters:
    
    - part: "Introduction"
      chapters:
        - index.qmd
        - evaluation.qmd

    - part: "Setting Up"
      chapters: 
        - activities/setup/Github_Account_Creation.qmd
        - activities/setup/Git_Clients.qmd
        
    - part: activities/class_1/Single-User-Project.qmd
      chapters: 
        - activities/class_1/local-history.qmd
        - activities/class_1/remote-history.qmd

    - part: "Multi-User Project"
      chapters: 
        - activities/class_1/collaborative-project.qmd

    - part: "Development Web Project"
      chapters: 
        - activities/Multi-User-Projet.md

number-depth: 3
fig-cap-location: bottom
lst-cap-location: bottom


website:
  title: "wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



